### ISSUE TITLE
备用积分库申请

### ISSUE THREAD

**Issue by zita-ch** [9-LADDER/discussions#7]
#  请将姓名、申请的备用积分项目、单项积分和总积分敲在下面    
##  如果发现自己打出来的东西太丑，建议百度github markdown语法，或更细的搜索，如markdown换行。

**Comment by zita-ch** [comment]
### 说明     
选手须先申请库以确定备用积分上限，之后的备用积分会自动从库中取出。

**Comment by zbh88** [comment]
张博涵   精93

ⅰ.报名参加新生机电设计大赛                                          5分

ⅱ.新生机电设计大赛通过中期筛选                                  3分

ⅲ. 新生机电设计大赛完赛                                               3分

ⅴ.参加精仪科协举办的培训                                            5分

ⅷ.参加过非精仪科协举办的科创比赛                             2分 

ⅸ.在非精仪科协举办的非三星级科创比赛中获得奖项   2分

共计：                                                                            20分

**Comment by libbthu** [comment]
李冰白

1、报名参加新生机电设计大赛  5分

5、参加精仪科协举办的培训  7分

共计：12分

**Comment by Deng-Jingyuan** [comment]
邓璟瑗 精92

ⅰ.报名参加新生机电设计大赛 5分

ⅱ.新生机电设计大赛通过中期筛选 3分

ⅲ. 新生机电设计大赛完赛 3分

ⅴ.参加精仪科协举办的培训 5分

共计： 16分

**Comment by TheConquerOfParadise** [comment]
李佐龙     精93
    1、报名参加新生机电设计大赛 5分
    2、新生机电设计大赛通过中期筛选 3分
    3、新生机电设计大赛完赛 3分
    4、参加精仪科协举办的培训 6分
    5、参加过非精仪科协举办的科创比赛 2分
    
    共计：19分

**Comment by GrandpaDrewK** [comment]
何奕彬 车辆91
报名参加新生机电设计大赛 5分
新生机电设计大赛通过中期筛选 3分
新生机电设计大赛完赛 3分
参加精仪科协举办的培训 7分
参加过非精仪科协举办的科创比赛 2分
共20分

**Comment by shiqr19** [comment]
时其然 精91

ⅰ.报名参加新生机电设计大赛 5分

ⅱ.新生机电设计大赛通过中期筛选 3分

ⅲ. 新生机电设计大赛完赛 3分

ⅴ.参加精仪科协举办的培训 6分

共计： 17分

**Comment by Mariana2000** [comment]
王谢衡 精93

1.报名参加新生机电设计大赛 5分<br>
2.新生机电设计大赛通过中期筛选 3分<br>
3.新生机电设计大赛完赛 3分<br>
4.参加精仪科协举办的培训 6分<br>

共计：**17分**

**Comment by elitemio** [comment]
钱彦 精93
参加过非精仪科协举办的科创比赛 2分
在非精仪科协举办的非三星级科创比赛中获得奖项 2分
共计： 4分

**Comment by hanyullai** [comment]
赖瀚宇 计92
参加过非精仪科协举办的科创比赛 2分
在非精仪科协举办的非三星级科创比赛中获得奖项 2分
在非精仪科协举办的三星级科创比赛中获得奖项 4分
共计：8分

**Comment by hanyullai** [comment]
赖瀚宇 计92
参加过非精仪科协举办的科创比赛 2分
在非精仪科协举办的非三星级科创比赛中获得奖项 2分
共计：4分

**Comment by Marfus01** [comment]
王琛 精93

ⅰ.报名参加新生机电设计大赛 5分

ⅱ.新生机电设计大赛通过中期筛选 3分

ⅲ. 新生机电设计大赛完赛 3分

ⅴ.参加精仪科协举办的培训 7分

共计： 18分

**Comment by liaozjzj** [comment]
廖子健  精91
5. 参加精仪科协举办的培训    6分
共计： 6分

**Comment by Yifei-827** [comment]
王艺霏 精93<br>参加精仪科协举办的培训 4分<br>共计： 4分

**Comment by DuZiyu** [comment]
杜子煜 精92

ⅰ.报名参加新生机电设计大赛 5分

ⅱ.新生机电设计大赛通过中期筛选 3分

ⅲ. 参加精仪科协举办的培训 5分

共计： 13分

**Comment by Yukinagi** [comment]
李子康 精92
报名参加新生机电设计大赛 5分
新生机电设计大赛通过中期筛选 3分
参加精仪科协举办的培训 5分
共计： 13分
